"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.FXDialogStyleInterceptorSystem = exports.resolveDialogActionKind = exports.resolveDialogContentKind = exports.checkIsDefaultAction = exports.checkIsCustomAction = exports.checkIsCustomContent = exports.FXDialogActionKind = exports.FXDialogContentKind = exports.FXDialogAnimationType = exports.FXDialogCloseSystemType = exports.FXDialogActionType = exports.FXDialogType = exports.FXDialogAnimation = exports.FXDialogView = exports.FXDialog = void 0;
var FXDialog_1 = require("./FXDialog");
Object.defineProperty(exports, "FXDialog", { enumerable: true, get: function () { return __importDefault(FXDialog_1).default; } });
var FXDialogView_1 = require("./FXDialogView");
Object.defineProperty(exports, "FXDialogView", { enumerable: true, get: function () { return __importDefault(FXDialogView_1).default; } });
var FXDialogAnimation_1 = require("./animation/FXDialogAnimation");
Object.defineProperty(exports, "FXDialogAnimation", { enumerable: true, get: function () { return FXDialogAnimation_1.FXDialogAnimation; } });
var types_1 = require("./types");
Object.defineProperty(exports, "FXDialogType", { enumerable: true, get: function () { return types_1.FXDialogType; } });
Object.defineProperty(exports, "FXDialogActionType", { enumerable: true, get: function () { return types_1.FXDialogActionType; } });
Object.defineProperty(exports, "FXDialogCloseSystemType", { enumerable: true, get: function () { return types_1.FXDialogCloseSystemType; } });
Object.defineProperty(exports, "FXDialogAnimationType", { enumerable: true, get: function () { return types_1.FXDialogAnimationType; } });
Object.defineProperty(exports, "FXDialogContentKind", { enumerable: true, get: function () { return types_1.FXDialogContentKind; } });
Object.defineProperty(exports, "FXDialogActionKind", { enumerable: true, get: function () { return types_1.FXDialogActionKind; } });
Object.defineProperty(exports, "checkIsCustomContent", { enumerable: true, get: function () { return types_1.checkIsCustomContent; } });
Object.defineProperty(exports, "checkIsCustomAction", { enumerable: true, get: function () { return types_1.checkIsCustomAction; } });
Object.defineProperty(exports, "checkIsDefaultAction", { enumerable: true, get: function () { return types_1.checkIsDefaultAction; } });
Object.defineProperty(exports, "resolveDialogContentKind", { enumerable: true, get: function () { return types_1.resolveDialogContentKind; } });
Object.defineProperty(exports, "resolveDialogActionKind", { enumerable: true, get: function () { return types_1.resolveDialogActionKind; } });
var FXDialogStyleInterceptor_1 = require("./style/FXDialogStyleInterceptor");
Object.defineProperty(exports, "FXDialogStyleInterceptorSystem", { enumerable: true, get: function () { return FXDialogStyleInterceptor_1.FXDialogStyleInterceptorSystem; } });
